application: projeto-mvc
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

handlers:

- url: /assets
  static_dir: assets

- url: /data
  static_dir: data

- url: /images
  static_dir: images

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
